---
- name: create vm demo
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
      - include_vars: vars.yml
  tasks:
      - name: create folder
        vcenter_folder:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: "{{ vcenter_validate_certs }}"
          datacenter_name: "{{ vcenter_datacenter }}"
          folder_name: "{{ vcenter_destination_folder }}"
          folder_type: vm
          state: present
      - name: create VM
        vmware_guest:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: "{{ vcenter_validate_certs }}"
          datacenter: "{{ vcenter_datacenter }}"
          name: "{{ vm_name }}"
          template: "{{ vm_template }}"
          folder: "{{ vcenter_destination_folder }}"
          state: "{{ vm_state }}"
          guest_id: "{{ vm_guestid }}"
          cluster: ""
          disk:
            - size_gb: "{{ vm_disk_gb }}"
              type: "{{ vm_disk_type }}"
              datastore: "{{ vm_disk_datastore }}"
          hardware:
            memory_mb: "{{ vm_hw_ram_mb }}"
            num_cpus: "{{ vm_hw_cpu_n }}"
            scsi: "{{ vm_hw_scsi }}"
          networks:
            - name: "{{ vm_net_name }}"
              device_name: "{{ vm_net_type }}"
              ip: 10.5.40.38
              netmask: 255.255.255.0
              gateway: 10.5.40.1
          wait_for_ip_address: True
          customization:
            autologon: true
            domain: "vsphere.local"
            dns_servers:
              - 8.8.8.8
            password: Jerico.4878
            runonce:
            - powershell.exe -ExecutionPolicy Unrestricted -File C:\Temp\prueba.ps1 -ForceNewSSLCert -EnableCredSSP
        delegate_to: localhost
